
/*import Head from 'next/head'
import Sections from '@/components/sections'
import {fetchAPI} from '@/utils/api'
export default function Home({data}) {
  return (
    <>
      <Head>
        <title>Strapi-Community</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Sections sections={data.data.attributes.sections}/>
    </>
  )
}

export async function getServerSideProps() {
  // Fetch data from external API
  const data = await fetchAPI("/pages/1",
  { 
    populate: {
      sections: { 
        on: {
          "slices.hero": { 
            populate: "*"
          },
          "slices.com-intro": {
            populate: "*"
          },
          "slices.why-join-us": {
            populate: {
              button: true,
              image: true,
              whyJoin: {
                populate: {
                  icon: true
                }
              }
            }
          },
          "slices.cta": {
            populate: "*"
          }
        }
      }
    }
  } )

  const headerData = await fetchAPI("/header",
  {
    populate: "*"
  })

  // Pass data to the page via props
  return { props: { data,headerData }}
}

/*
    <>
      <Head>
        <title>Strapi-Community</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Hero />
      <MainContainer>
        <ComIntro />
        <WhyJoinUs />
        <div className="pt-32">
          <CtaBounty />
        </div>
        <LatestNews />
        <RelevantTopics />
        <Newsletter />
      </MainContainer>
    </>
    */