import Head from "next/head";

import MainContainer from "@/components/atoms/MainContainer";
import AboutCom from "@/components/sections/about/AboutCom";
import Resources from "@/components/sections/about/Resources";
import Hero from "@/components/sections/about/Hero"
import MeetCommunity from "@/components/sections/about/MeetCommunity";
import WhyJoinUs from "@/components/sections/WhyJoinUs";
import Newsletter from "@/components/sections/Newsletter";
import CtaBounty from "@/components/sections/CtaBounty";
import ActiveContributors from "@/components/sections/about/ActiveContributors";

export default function AboutUs() {
  return (
    <>
      <Head>
        <title>Strapi-Community - About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/strapi-.svg" />
      </Head>
      <Hero />
      <MainContainer>
        <Resources />
        <AboutCom />
        <WhyJoinUs />
        <MeetCommunity />
        <ActiveContributors/>
        <section className="pt-32">
          <CtaBounty />
        </section>
        <Newsletter/>
      </MainContainer>
    </>
  )
}
