
import Head from 'next/head'
import Sections from '@/components/sections'
import {fetchAPI} from '@/lib/api'
export default function Home({data}) {
  return (
    <>
      <Head>
        <title>Strapi-Community</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Sections sections={data.data.attributes.sections}/>
    </>
  )
}

export async function getServerSideProps() {
  // Fetch data from external API
  const data = await fetchAPI("/pages/1",
  { 
    populate: {
      sections: { 
        on: {
          "slices.hero": { 
            populate: {
              button: true,
              image: true
            }
          }
        }
      }
    }
  } )

  // Pass data to the page via props
  return { props: { data } }
}
