
import Head from 'next/head'

import MainContainer from '@/components/atoms/MainContainer'
import Newsletter from '@/components/sections/Newsletter'
import ComIntro from '@/components/sections/home/ComIntro'
import Hero from '@/components/sections/home/Hero'
import LatestNews from '@/components/sections/home/LatestNews'
import RelevantTopics from '@/components/sections/home/RelevantTopics'
import WhyJoinUs from '@/components/sections/WhyJoinUs'
import CtaBounty from '@/components/sections/CtaBounty'

export default function Home() {
  return (
    <>
      <Head>
        <title>Strapi-Community</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Hero />
      <MainContainer>
        <ComIntro />
        <WhyJoinUs />
        <div className="pt-32">
          <CtaBounty />
        </div>
        <LatestNews />
        <RelevantTopics />
        <Newsletter />
      </MainContainer>
    </>
  )
}
