const contents = [
  {
    id: 1,
    title: 'How To Build A Strapi Custom Field For Text Generation With Open AI',
    body: 'Discover how to build a Strapi Custom Field to leverage AI for content creation in your Strapi application.',
    level: 'INTERMEDIATE',
    imageSrc: 'https://d2zv2ciw0ln4h1.cloudfront.net/uploads/Building_a_Strapi_Custom_Field_for_Text_Generation_with_Open_AI_781a28da93.png',
    readMins: 9,
    author: 'Daniel Madalitso Phiri',
    date: 'February 7, 2023',
  },
  {
    id: 2,
    title: 'How to Deploy and Scale Strapi on a Kubernetes Cluster 2/2',
    body: 'Discover how to integrate Strapi with Kubernetes through a comprehensive, step-by-step tutorial series. Explore the process from building your image to deploying a highly available and robust application.',
    level: 'ADVANCED',
    imageSrc: 'https://d2zv2ciw0ln4h1.cloudfront.net/uploads/How_to_Deploy_and_Scale_Strapi_on_a_Kubernetes_Cluster_Part_II_bd476306f0.png',
    readMins: 28,
    author: 'José Alfredo Alvarez Aldana',
    date: 'February 3, 2023',
  },
  {
    id: 3,
    title: 'How to Deploy and Scale Strapi on a Kubernetes Cluster 1/2',
    body: 'Discover how to integrate Strapi with Kubernetes through a comprehensive, step-by-step tutorial series. Explore the process from building your image to deploying a highly available and robust application.',
    level: 'ADVANCED',
    imageSrc: 'https://d2zv2ciw0ln4h1.cloudfront.net/uploads/How_to_Deploy_and_Scale_Strapi_on_a_Kubernetes_Cluster_Part_I_67d1ea762f.png',
    readMins: 9,
    author: 'José Alfredo Alvarez Aldana',
    date: 'February 3, 2023',
  },
  {
    id: 4,
    title: 'Goodbye 2022, Hello 2023!',
    body: "2022 was a big year for Strapi, with insane achievements. From 200+ product releases to community growth. Discover the past year's successes and what is coming to an even brighter future.",
    level: '',
    imageSrc: 'https://d2zv2ciw0ln4h1.cloudfront.net/uploads/Goodbye_2022_Hello_2023_142c05547c.png',
    readMins: 13,
    author: 'Pierre Burgy',
    date: 'January 30, 2023',
  },
  {
    id: 5,
    title: 'Introducing Strapi v4.6 with Data export & import, relations and component reordering, audit logs and more',
    body: "Strapi evolves fast, and we're excited to announce a fresh v4.6 with new features that make both development and content management experience better.",
    level: '',
    imageSrc: 'https://d2zv2ciw0ln4h1.cloudfront.net/uploads/Blog_cover_template_v4_6_43b165132d.png',
    readMins: 6,
    author: 'Anastasiia Shpiliak',
    date: 'February 7, 2023',
  },
  {
    id: 6,
    title: 'Introducing Strapi v4.6 with Data export & import, relations and component reordering, audit logs and more',
    body: "Strapi evolves fast, and we're excited to announce a fresh v4.6 with new features that make both development and content management experience better.",
    level: '',
    imageSrc: 'https://d2zv2ciw0ln4h1.cloudfront.net/uploads/Blog_cover_template_v4_6_43b165132d.png',
    readMins: 6,
    author: 'Anastasiia Shpiliak',
    date: 'February 7, 2023',

  },
  {
    id: 7,
    title: 'A Quick Introduction to Micro Frontend using Module Federation',
    body: 'Learn what Micro Frontend is, its advantages, and how it works by sharing its state within two applications using Module Federation.',
    level: 'BEGINNER',
    imageSrc: 'https://d2zv2ciw0ln4h1.cloudfront.net/uploads/A_Quick_Introduction_to_Micro_Frontend_using_Module_Federation_d3a871f082.png',
    readMins: 13,
    author: 'Temitope Oyedele',
    date: 'January 20, 2023',
  },

  {
    id: 8,
    title: 'How to Quickly Get Started with Strapi Using Azure ARM Templates',
    body: 'Learn with an automated (Infrastructure as Code) approach to create an Azure Virtual Machine and install Strapi on it.',
    level: 'BEGINNER',
    imageSrc: 'https://d2zv2ciw0ln4h1.cloudfront.net/uploads/How_to_Quickly_Get_Started_with_Strapi_Using_Azure_ARM_templates_abd8af9c3a.png',
    readMins: 4,
    author: 'Sangram Rath',
    date: 'January 19, 2023',
  },

  {
    id: 9,
    title: 'Incremental Static Regeneration in Next.js with Strapi',
    body: 'Learn how Strapi implemented Incremental Static Regeneration in Next.js combined with the webhook feature for near-instant updates. Discover how Cloudfront caching and revalidation routes were used for improved website performance for users.',
    level: 'ECOSYSTEM',
    imageSrc: 'https://d2zv2ciw0ln4h1.cloudfront.net/uploads/Blog_cover_template_v4_6_43b165132d.png',
    readMins: 3,
    author: 'Maxime Castres',
    date: 'January 18, 2023',
  },
  {
    id: 10,
    title: 'Migrating Content Between Environments Using Import Export Entries Plugin',
    body: 'Learn how to migrate data from one environment to another using the Import Export Entries plugin.',
    level: 'BEGINNER',
    imageSrc: 'https://d2zv2ciw0ln4h1.cloudfront.net/uploads/Migrating_Content_Between_Environments_Using_Import_Export_Entries_Plugin_6b04329d57.png',
    readMins: 6,
    author: 'Abdulwahab Ashimi',
    date: 'January 11, 2023',
  },
  {
    id: 11,
    title: 'How to Create a Book Rating App with Strapi Ratings Plugin and Cloudinary',
    body: 'Learn how to create a book rating application. This tutorial will introduce you to Cloudinary, Next.js, implementing a WYSIWYG editor, Strapi custom controllers, middleware, and policies.',
    level: 'INTERMEDIATE',
    imageSrc: 'https://d2zv2ciw0ln4h1.cloudfront.net/uploads/How_Create_a_Book_Rating_App_with_Strapi_Ratings_Plugin_and_Cloudinary_143ea25703.png',
    readMins: 6,
    author: 'Theodore Kelechukwu Onyejiaku',
    date: 'January 10, 2023',
  },

  {
    id: 12,
    title: 'How To Add Unit Tests To Your Strapi Plugin',
    body: 'In this article, you will learn how to add unit tests using the Jest testing framework to your Strapi plugin.',
    level: 'INTERMEDIATE',
    imageSrc: 'https://d2zv2ciw0ln4h1.cloudfront.net/uploads/How_To_Add_Unit_Tests_To_Your_Strapi_Plugin_97752d39a9.png',
    readMins: 6,
    author: 'Anastasiia Shpiliak',
    date: 'February 7, 2023',
  },
];

export default contents;
